# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ToDoList.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle("japar's To-Do List")
        MainWindow.resize(800, 636)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 581))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.TaskLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.TaskLabel.setObjectName("TaskLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.TaskLabel)
        self.txt_task = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_task.setObjectName("txt_task")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_task)
        self.PriorityLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.PriorityLabel.setObjectName("PriorityLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.PriorityLabel)
        self.cmb_priority = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cmb_priority.setObjectName("cmb_priority")
        self.cmb_priority.addItem("")
        self.cmb_priority.setItemText(0, "")
        self.cmb_priority.addItem("Rendah")
        self.cmb_priority.addItem("Sedang")
        self.cmb_priority.addItem("Tinggi")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cmb_priority)
        self.DateLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.DateLabel.setObjectName("DateLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.DateLabel)
        self.date_due_date = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.date_due_date.setCalendarPopup(True)
        self.date_due_date.setDisplayFormat("dd/MM/yyyy")
        self.date_due_date.setSpecialValueText("--/--/----")
        self.date_due_date.setDate(QtCore.QDate(1, 1, 1))
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.date_due_date)
        self.dayLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.dayLabel.setObjectName("dayLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.dayLabel)
        self.cmb_day = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cmb_day.setObjectName("cmb_day")
        self.cmb_day.addItem("")
        self.cmb_day.setItemText(0, "")
        self.cmb_day.addItem("Senin")
        self.cmb_day.addItem("Selasa")
        self.cmb_day.addItem("Rabu")
        self.cmb_day.addItem("Kamis")
        self.cmb_day.addItem("Jumat")
        self.cmb_day.addItem("Sabtu")
        self.cmb_day.addItem("Minggu")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cmb_day)
        self.JamLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.JamLabel.setStyleSheet("font: 8pt \"Poppins\";")
        self.JamLabel.setObjectName("JamLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.JamLabel)
        self.time_due_time = QtWidgets.QTimeEdit(self.formLayoutWidget)
        self.time_due_time.setDisplayFormat("HH:mm")
        self.time_due_time.setSpecialValueText("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.time_due_time)
        self.InfoLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.InfoLabel.setObjectName("InfoLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.InfoLabel)
        self.txt_description = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_description.setObjectName("txt_description")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txt_description)
        self.btn_add_task = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_add_task.setObjectName("btn_add_task")
        self.btn_add_task.setStyleSheet("background-color: #333; color: white; font-size: 12pt; padding: 10px; border-radius: 5px;")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.btn_add_task)
        self.table_todo = QtWidgets.QTableWidget(self.formLayoutWidget)
        self.table_todo.setColumnCount(6)
        self.table_todo.setHorizontalHeaderLabels(["🗑️", "Tugas", "Prioritas", "Tanggal", "Deadline", "Keterangan"])
        self.table_todo.setObjectName("table_todo")
        self.table_todo.verticalHeader().setVisible(False)
        header = self.table_todo.horizontalHeader()
        header.setStretchLastSection(False)
        header.setSectionResizeMode(QtWidgets.QHeaderView.Interactive)
        self.table_todo.setColumnWidth(0, 50)
        self.table_todo.setColumnWidth(1, 150)
        self.table_todo.setColumnWidth(2, 100)
        self.table_todo.setColumnWidth(3, 200)
        self.table_todo.setColumnWidth(4, 100)
        self.table_todo.setColumnWidth(5, 250)
        self.table_todo.setStyleSheet("border: 1px solid #ddd; background-color: #f7f7f7; font-size: 10pt;")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.table_todo)
        self.btn_clear_task = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_clear_task.setObjectName("btn_clear_task")
        self.btn_clear_task.setStyleSheet("background-color: #333; color: white; font-size: 12pt; padding: 10px; border-radius: 5px;")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.btn_clear_task)
        self.id_student = QtWidgets.QLabel(self.formLayoutWidget)
        self.id_student.setEnabled(False)
        self.id_student.setAlignment(QtCore.Qt.AlignCenter)
        self.id_student.setObjectName("id_student")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.id_student)
        self.Copyright = QtWidgets.QLabel(self.formLayoutWidget)
        self.Copyright.setEnabled(False)
        self.Copyright.setAlignment(QtCore.Qt.AlignCenter)
        self.Copyright.setObjectName("Copyright")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.Copyright)
        self.lbl_title = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_title.setStyleSheet("font-size: 20pt; font-weight: bold; margin: 10px;")
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.lbl_title)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "japar's To-Do List"))
        self.TaskLabel.setText(_translate("MainWindow", "Tugas"))
        self.PriorityLabel.setText(_translate("MainWindow", "Prioritas"))
        self.DateLabel.setText(_translate("MainWindow", "Tanggal"))
        self.dayLabel.setText(_translate("MainWindow", "Hari"))
        self.JamLabel.setText(_translate("MainWindow", "Jam"))
        self.InfoLabel.setText(_translate("MainWindow", "Keterangan"))
        self.btn_add_task.setText(_translate("MainWindow", "Add"))
        self.btn_clear_task.setText(_translate("MainWindow", "Clear All"))
        self.id_student.setText(_translate("MainWindow", "Muhammad Fajar Maulana | F1D022072"))
        self.Copyright.setText(_translate("MainWindow", "Copyright © 2025 Japar"))
        self.lbl_title.setText(_translate("MainWindow", "To-Do List 📝"))

class MainApp(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.setup_connections()

    def setup_connections(self):
        self.ui.btn_add_task.clicked.connect(self.add_task)
        self.ui.btn_clear_task.clicked.connect(self.clear_tasks)
        self.ui.table_todo.cellClicked.connect(self.delete_task)

    def add_task(self):
        task = self.ui.txt_task.text()
        priority = self.ui.cmb_priority.currentText()
        day = self.ui.cmb_day.currentText()
        date = self.ui.date_due_date.text()
        time = self.ui.time_due_time.text()
        description = self.ui.txt_description.text()

        if not all([task.strip(), priority.strip(), day.strip(), description.strip()]) or date == "--/--/----" or time == "--:--" or time.strip() == "":
            QtWidgets.QMessageBox.warning(self, "Peringatan", "Semua field harus diisi dengan benar!")
            return

        row_position = self.ui.table_todo.rowCount()
        self.ui.table_todo.insertRow(row_position)

        delete_btn = QtWidgets.QPushButton("❌")
        delete_btn.clicked.connect(lambda _, row=row_position: self.delete_row(row))
        self.ui.table_todo.setCellWidget(row_position, 0, delete_btn)

        self.ui.table_todo.setItem(row_position, 1, QtWidgets.QTableWidgetItem(task))
        self.ui.table_todo.setItem(row_position, 2, QtWidgets.QTableWidgetItem(priority))
        self.ui.table_todo.setItem(row_position, 3, QtWidgets.QTableWidgetItem(f"{day}, {date}"))
        self.ui.table_todo.setItem(row_position, 4, QtWidgets.QTableWidgetItem(time))
        self.ui.table_todo.setItem(row_position, 5, QtWidgets.QTableWidgetItem(description))

        self.ui.txt_task.clear()
        self.ui.cmb_priority.setCurrentIndex(0)
        self.ui.cmb_day.setCurrentIndex(0)
        self.ui.date_due_date.setDate(QtCore.QDate(1, 1, 1))  
        self.ui.time_due_time.setTime(QtCore.QTime(0, 0))
        self.ui.txt_description.clear()

    def delete_row(self, row):
        self.ui.table_todo.removeRow(row)

    def delete_task(self, row, column):
        if column == 0:
            self.ui.table_todo.removeRow(row)

    def clear_tasks(self):
        self.ui.table_todo.setRowCount(0)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = MainApp()
    window.show()
    sys.exit(app.exec_())
